### ISSUE TITLE
Merge Code: UI & Search Branch

### ISSUE THREAD

**Issue by ghost** [OpenDataSTL/backyard-chickens#1]
Need to merge search and UI branches together to finish backyard-chickens

**Comment by ghost** [comment]
Blocked by: [Address in url isn't reflecting on interactive map bug](https://github.com/OpenDataSTL/backyard-chickens/issues/2)

**Comment by zacharyrgonzales** [comment]
> Need to merge search and UI branches together to finish backyard-chickens

Code merged
