### ISSUE TITLE
Navigation: "About", "Resources", "Gallery"

### ISSUE THREAD

**Issue by gavinr** [OpenDataSTL/backyard-chickens#20]
There are three links at the top:

![image](https://user-images.githubusercontent.com/209355/49595528-c51af680-f93d-11e8-9491-4ce22862b827.png)

What's our plan for the content of each? If we don't have content for any of them, we could remove that one temporarily until we have content to fill.

**Comment by AvidDabbler** [comment]
I'm on board with getting rid of the gallery link. I don't really know what we would do with that. I think that i would like to see the about link track down the page and state the purpose and plug openstl. Resources should do the same thing and just list out the docs with links to show our work.

**Comment by AvidDabbler** [comment]
@gavinr sorry i just got around to looking at this, but does it make more sense to bootstrap this first or is it 6 1/2 dozen?

**Comment by gavinr** [comment]
@CadillacJenkins I'd say either way -- switching to bootstrap first would be slightly more efficient, but is a bigger effort so if we want to do just put a fix in for this in the mean time, that's fine too.
