### ISSUE TITLE
Link to GitHub page from site

### ISSUE THREAD

**Issue by gavinr** [OpenDataSTL/backyard-chickens#23]
Would be good to have a link back to our github page (https://github.com/OpenDataSTL/backyard-chickens) on the website so people can see how the site is made, log issues, and participate if they would like.

We could put this in the footer or use a "fork me on github" github ribbon: https://blog.github.com/2008-12-19-github-ribbons/

**Comment by AvidDabbler** [comment]
issue resolved with #35
