### ISSUE TITLE
Chicken count logic is broken for some edge cases

### ISSUE THREAD

**Issue by brclark** [OpenDataSTL/backyard-chickens#27]
`calcCityChickens` was giving 99 chickens for some coup and fence examples.

<img width="1440" alt="screenshot 2018-12-11 20 56 25" src="https://user-images.githubusercontent.com/1033598/49844216-a24a7100-fd87-11e8-983e-0f889fc91568.png">

**Comment by AvidDabbler** [comment]
issue was fixed with #32
