### ISSUE TITLE
address search needs auto complete

### ISSUE THREAD

**Issue by AvidDabbler** [OpenDataSTL/backyard-chickens#4]

**Comment by ghost** [comment]
OpenStreetMap does not provide any kind of type-ahead geocoder or address search. We'll need to create our own data set. 

src - https://help.openstreetmap.org/questions/31809/auto-complete-address-using-web-service

**Comment by AvidDabbler** [comment]
Mapbox geocoding service is offered to free by CFA. We should move forward with revising architecture. using osm or outside service to create an "autocomplete" geocoding service would have required us to create and host our own database.
